<?php
/**
 * KillTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CryoFallStatisticsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CryoFall Statistics API
 *
 * This is an awesome app!
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CryoFallStatisticsApiClient;

/**
 * KillTest Class Doc Comment
 *
 * @category    Class
 * @description Kill
 * @package     CryoFallStatisticsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KillTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Kill"
     */
    public function testKill()
    {
    }

    /**
     * Test attribute "player"
     */
    public function testPropertyPlayer()
    {
    }

    /**
     * Test attribute "kills"
     */
    public function testPropertyKills()
    {
    }
}
