<?php
/**
 * ServerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CryoFallStatisticsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CryoFall Statistics API
 *
 * This is an awesome app!
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CryoFallStatisticsApiClient;

use CryoFallStatisticsApiClient\Configuration;
use CryoFallStatisticsApiClient\ApiException;
use CryoFallStatisticsApiClient\ObjectSerializer;

/**
 * ServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  CryoFallStatisticsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getLeaderboardAction
     *
     * .
     *
     */
    public function testGetLeaderboardAction()
    {
    }

    /**
     * Test case for getOnlineAction
     *
     * .
     *
     */
    public function testGetOnlineAction()
    {
    }
}
